### ISSUE TITLE
DIALDroid not working

### ISSUE THREAD

**Issue by vineetajain11** [dialdroid-android/DIALDroid#1]
I am trying to run DIALDroid on a set of APK's with the following command:

./dialdroid.sh apks/ DUMMY

I am getting the following error:

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 5
	at com.yaogroup.collusion.AppAnalysis.main(AppAnalysis.java:80)
	... 5 more

Kindly guide how to execute it.

**Comment by amiangshu** [comment]
The error is at: https://github.com/dialdroid-android/DIALDroid/blob/master/src/com/yaogroup/collusion/AppAnalysis.java#L80 

DialDroid is trying to parse the category name, which is the sixth argument to the dialdroid.jar. You need to set the android sdk path, dbname, and dbhost in dialdroid.sh.

Did you modify the dialdroid.sh correctly?

**Comment by JoyMitra** [comment]
@amiangshu there is no dbhost variable in the dialdroid.sh script. Where should I set it?

**Comment by amiangshu** [comment]
I think you are using the dialdroid.sh in the root folder. Please use the script inside the build directory. https://github.com/dialdroid-android/DIALDroid/blob/master/build/dialdroid.sh

**Comment by JoyMitra** [comment]
ah! thanks. I created an issue for this as well. You can close it if you want
